require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1.3
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/schema.rb
    - vendor/**/*

RSpec/FilePath:
  Exclude:
    - spec/entities/**/*_spec.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/Documentation:
  Enabled: false

RSpec/ExpectChange:
  Enabled: false

RSpec/MissingExampleGroupArgument:
  Enabled: false

Rails/DynamicFindBy:
  Enabled: false

Rails/ActiveRecordAliases:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

Metrics/AbcSize:
  Exclude:
    - spec/helpers/repositories/**/*.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/**/*.rb
    - spec/helpers/repositories/**/*.rb
