name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  BUNDLE_WITHOUT: development
  DATABASE_USER: ci
  DATABASE_PASSWORD: password
  RAILS_ENV: test

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      database:
        image: postgres:15.2-alpine
        env:
          POSTGRES_USER: ${{ env.DATABASE_USER }}
          POSTGRES_PASSWORD: ${{ env.DATABASE_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.144.2
        with:
          ruby-version: 3.1.3
          bundler-cache: true

      - name: Setting up DB
        run: bin/rails db:create db:schema:load

      - name: Checking constants consistency
        run: bin/rails zeitwerk:check

      - name: Checking code style
        run: bin/rubocop

      - name: Tests
        run: bin/rspec
